### ISSUE TITLE
Nametag isn’t aligned properly with my head

### ISSUE THREAD

**Issue by SimWasHere** [FxllenCode/RobloxNametagOS#2] opened 2021-04-25 19:01 UTC
The nametag is moved to the right; instead of being in the center
I have no idea how these nametags work, but you could possibly make a part that is slightly above the head and put the nametag there?

Preview: https://i.imgur.com/a2EQhlh.png

**Comment by FxllenCode** [comment] 2021-04-25 19:07
This is interesting!

I think (could be wrong here) it's based on the package you have on. Could you try with a different avatar?

Also, is it possible to send a screenshot of the console? Thanks!

**Comment by SimWasHere** [comment] 2021-04-25 19:13
There are no errors in the Dev Console (Client and Server)
I think it was about the specific head package I was using (junkbot)

ANDDD I also think I found another bug (1, maybe 2):
When I reset, I don't get my nametag back, which is kindaaaa bad (unless I did something wrong)
When I move my camera around the nametag moves too (not sure if this intentional)

**Comment by FxllenCode** [comment] 2021-05-06 12:53
Hi @SimWasHere

I see that there are 3 issues here; some bugs some intended behaviors.

1. (Original Problem) **Nametag isn't aligned correctly.** Unfortunately, this issue is not a top priority until I think of a better way to solve this. Certain packages do not work well with this as the attachments for the head (which I am using) are off-center from where they, in theory, should be. 
2. **No nametag on reset.** This issue is currently my top priority as this was an oversight on my part. I'm currently busy with finals but I'll work on it when I have time.
3. **Camera Moving nametag.** This is the intended behavior of roact, it is annoying but at this time it's not a top priority. 

Thanks for submitting an issue; your feedback is invaluable! 😀 

(I'll be closing this as the issue in OP is not going to be fixed anytime soon.)

**Closed as completed by FxllenCode** 2021-05-06 12:53 UTC
Labels: bug, good first issue, wontfix
